# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

CMakeFiles/hello_world_client.dir/hello_world_client.cpp.o: hello_world_client.cpp
CMakeFiles/hello_world_client.dir/hello_world_client.cpp.o: /usr/local/lib/cmake/vsomeip/../../../include/vsomeip/application.hpp
CMakeFiles/hello_world_client.dir/hello_world_client.cpp.o: /usr/local/lib/cmake/vsomeip/../../../include/vsomeip/constants.hpp
CMakeFiles/hello_world_client.dir/hello_world_client.cpp.o: /usr/local/lib/cmake/vsomeip/../../../include/vsomeip/defines.hpp
CMakeFiles/hello_world_client.dir/hello_world_client.cpp.o: /usr/local/lib/cmake/vsomeip/../../../include/vsomeip/enumeration_types.hpp
CMakeFiles/hello_world_client.dir/hello_world_client.cpp.o: /usr/local/lib/cmake/vsomeip/../../../include/vsomeip/export.hpp
CMakeFiles/hello_world_client.dir/hello_world_client.cpp.o: /usr/local/lib/cmake/vsomeip/../../../include/vsomeip/function_types.hpp
CMakeFiles/hello_world_client.dir/hello_world_client.cpp.o: /usr/local/lib/cmake/vsomeip/../../../include/vsomeip/handler.hpp
CMakeFiles/hello_world_client.dir/hello_world_client.cpp.o: /usr/local/lib/cmake/vsomeip/../../../include/vsomeip/internal/deserializable.hpp
CMakeFiles/hello_world_client.dir/hello_world_client.cpp.o: /usr/local/lib/cmake/vsomeip/../../../include/vsomeip/internal/serializable.hpp
CMakeFiles/hello_world_client.dir/hello_world_client.cpp.o: /usr/local/lib/cmake/vsomeip/../../../include/vsomeip/message.hpp
CMakeFiles/hello_world_client.dir/hello_world_client.cpp.o: /usr/local/lib/cmake/vsomeip/../../../include/vsomeip/message_base.hpp
CMakeFiles/hello_world_client.dir/hello_world_client.cpp.o: /usr/local/lib/cmake/vsomeip/../../../include/vsomeip/payload.hpp
CMakeFiles/hello_world_client.dir/hello_world_client.cpp.o: /usr/local/lib/cmake/vsomeip/../../../include/vsomeip/primitive_types.hpp
CMakeFiles/hello_world_client.dir/hello_world_client.cpp.o: /usr/local/lib/cmake/vsomeip/../../../include/vsomeip/runtime.hpp
CMakeFiles/hello_world_client.dir/hello_world_client.cpp.o: /usr/local/lib/cmake/vsomeip/../../../include/vsomeip/vsomeip.hpp

